### ISSUE TITLE
계산도우미 정산 내역 중앙 정렬 안됨

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#19]
계산도우미 정산 내역 가로로 긴 스크린에서 왼쪽으로 치우치는 문제 발생

**Comment by Lee-Jun-Young** [comment]
![image](https://github.com/prography-8th-6team/android/assets/47595801/d9c2327a-fd79-4524-8fe1-0db32dcad7eb)
태블릿으로 봐서 문제일 수도 있지만 수정하면 좋을듯???

**Comment by Ddudduu** [comment]
오케이!!

**Comment by Lee-Jun-Young** [comment]
작업할게!

**Comment by Ddudduu** [comment]
속성을 하나 바꾸긴했는데 수정된 건지 잘 모르겠어서..! 확인 해주면 고마울 것 같아!!! 😅

**Comment by Lee-Jun-Young** [comment]
지금 dev에 올려놓은걸까??? gravity center주면 되긴할거야

**Comment by Ddudduu** [comment]
앗 상단 그래프에만 gravity 설정해놓은 것 같아..! 수정해야될 것 같아!!

**Comment by Lee-Jun-Young** [comment]
ll_balance에 gravity center 주면 될듯한데 한번 확인 후 피알 부탁해!!

**Comment by Ddudduu** [comment]
오키!!
