### ISSUE TITLE
여행 리스트화면 버튼 동작 필요(여행리스트 상단, 우측)

### ISSUE THREAD

**Issue by Lee-Jun-Young** [prography-8th-6team/android#30]
- 이건 버그라기 보다는 아직 기능이 없는거긴 한데 그래도 이슈 등록은 해놓을게 잊지 않기 위해서...

![image](https://github.com/prography-8th-6team/android/assets/47595801/64e31ca5-f49b-4f58-b7d4-664f999ace2d)

**Comment by Ddudduu** [comment]
오키!!! 👍👍
