### ISSUE TITLE
구글 play service json 추가

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#41]
json 파일이 누락돼서 빌드가 안되는데, 까먹지 않게 이슈로 추가해둘게!

**Comment by Lee-Jun-Young** [comment]
저녁에 포함해서 올릴게!

**Comment by Lee-Jun-Young** [comment]
앱 이름을 바꿔서 그런 걸 수도 있을 것 같아(파이어베이스에서 json 파일 다운받을때의 이름과 지금 이름이 달라서??)

**Comment by Lee-Jun-Young** [comment]
다시 풀 받아서 빌드해보고 되면 닫아줘!!

**Comment by Ddudduu** [comment]
빌드 잘 된다! 이슈 닫을게~! 땡큐땡큐
