### ISSUE TITLE
여행 초대 링크 공유 시, dynamic link not found

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#57]
- 여행 생성 후, 링크 복사 후 공유하면 dynamic link not found 창이 뜸
- dynamic link 부분 다시 확인하기

![image](https://github.com/prography-8th-6team/android/assets/50603005/cf9922ed-fdda-4300-add8-fa7eade4f345)

**Comment by Lee-Jun-Young** [comment]
이거 우리가 전에 심사 올린다고 패키지명 바꾼적이 있었는데 파이어베이스에는 전 패키지명으로 등록해놔서 못찾는게 아닐까 하는 생각이....... 
이 부분 우선순위 좀 높게 잡고 볼게!!
