### ISSUE TITLE
앱 이름 져니리스트 -> 저니리스트

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#59]
- 앱 설치 시 져니리스트 -> 저니리스트
- 저니리스트 가 맞음!
<img src="https://github.com/prography-8th-6team/android/assets/50603005/97f5ee50-b807-4f73-91a0-e0ff0f9b018f" width="200" height="400"/>

<br/>
<img src="https://github.com/prography-8th-6team/android/assets/50603005/8782bdf1-e24e-4a77-bfff-d26df60a4b4f" width="130" height="130"/>

**Comment by Lee-Jun-Young** [comment]
이거는 다음 배포 나갈 때 수정할게!!
