### ISSUE TITLE
메인 -> 좌측 상단 드로어블 -> 로그아웃 추가

### ISSUE THREAD

**Issue by Lee-Jun-Young** [prography-8th-6team/android#63]
로그인은 하는데 로그아웃이 없어서 추가하는게 맞다고 생각하는데 어떻게 생각해??

**Comment by Ddudduu** [comment]
응 있어야할 것 같아! 앱 내에 저장돼있는 토큰 날리고 온보딩 액티비티로 전환하면 될까? 아니면 서버에 로그아웃 api 만들어달라고 요청해야 하나?.?

**Comment by Lee-Jun-Young** [comment]
토큰 날리고 로그인 화면으로 이동시키면 될 것 같아!!
