### ISSUE TITLE
여행 상세 -> 일정 탭 리스트 없는 경우에는 수정 텍스트 미노출

### ISSUE THREAD

**Issue by Lee-Jun-Young** [prography-8th-6team/android#65]
- 리스트가 없을 때는 수정 텍스트 미노출 처리가 필요할 것 같아!!

**Comment by Ddudduu** [comment]
앗 오케이!!!
해당 날짜에 일정이 없는 경우 "일정이 없습니다" 이런 텍스트도 띄워주는 게 좋겠지?

**Comment by Lee-Jun-Young** [comment]
장바구니, 일정 리스트 둘다 그렇게 처리하면 좋을 것 같아!!

**Comment by Lee-Jun-Young** [comment]
위에 새로운 이슈 만든 거 같아서 닫을게!
