### ISSUE TITLE
여행 날짜 형식 수정

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#76]
- 현재는 23-10-02 - 23-10-10 으로 되어있는데 23.10.02 - 23.10.10 형식으로 수정 필요

**Comment by Ddudduu** [comment]
- 여행 리스트, 가계부 생성에서도 수정 필요

**Comment by Lee-Jun-Young** [comment]
데이트 포맷 -을 .으로 바꿀게!
