### ISSUE TITLE
가계부 -> 비용 추가 오류

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#77]
- 비용 입력 후 엔터 클릭 안하면, 1/N 에서 멤버 선택 시 비용이 0.0 으로 변경됨
(입력만 하고 엔터 안 누르면 적용 안되는 게 맞는지?)

**Comment by Ddudduu** [comment]
- 비용 추가 api 호출이 안되는 경우가 있음 (확인 필요!)

**Comment by Lee-Jun-Young** [comment]
>

**Comment by Lee-Jun-Young** [comment]
> * 비용 입력 후 엔터 클릭 안하면, 1/N 에서 멤버 선택 시 비용이 0.0 으로 변경됨
>   (입력만 하고 엔터 안 누르면 적용 안되는 게 맞는지?)

맞아. 이 부분이 저번에 말했던 ime_action 부분이라서 수정할게!

**Comment by Lee-Jun-Young** [comment]
> * 비용 입력 후 엔터 클릭 안하면, 1/N 에서 멤버 선택 시 비용이 0.0 으로 변경됨
>   (입력만 하고 엔터 안 누르면 적용 안되는 게 맞는지?)

1/N에서 멤버

**Comment by Ddudduu** [comment]
아하 이부분이구나! 오케이 오케이!
