### ISSUE TITLE
여행 리스트 수정 -> 끝 날짜 데이트 피커 디폴트 날짜

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#79]
- 현재는 끝 날짜 데이트 피커 디폴트 날짜가 시작 날짜로 설정돼있는데, 기존 끝 날짜로 보여줘야 할 것 같음

**Comment by Lee-Jun-Young** [comment]
![image](https://github.com/prography-8th-6team/android/assets/47595801/91b59c59-f68d-4be9-8ac8-3472c58269db)
이부분에서 초기값 세팅해주는 거 같아서 고쳤는데 한번 확인 해주라~

**Comment by Ddudduu** [comment]
네넵!!
