### ISSUE TITLE
가계부 -> 비용 수정 시 반영 안됨

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#81]
- 리스트 아이템과 상세페이지 상단 금액에서는 수정한 금액이 반영 안됨 (원래 금액으로 보여짐)
- 상세 페이지 하단 금액에서는 수정된 금액으로 표시됨

**Comment by Lee-Jun-Young** [comment]
이거는 api에서 내려주는거 상세에 뿌려주고 있는데 백엔드 로직에서 총 금액을 수정하지 않을 가능성도 있는 것 같아. 저녁에 다시한번 보고 확인 요청할게!!

**Comment by Lee-Jun-Young** [comment]
이거 형준이가 해결해줘서 닫기할게!!
