### ISSUE TITLE
가계부 -> 비용 수정시 앱 종료됨

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#82]
- NPE 발생
<img width="538" alt="image" src="https://github.com/prography-8th-6team/android/assets/50603005/4958b0ba-b810-4214-8110-2318fbc50fe1">

- 로그를 따라가보면 화폐 validate 하는 부분에서 발생하는 것 같음!
<img width="324" alt="image" src="https://github.com/prography-8th-6team/android/assets/50603005/8afa1329-3a88-40b1-bfdc-4b2167f967ee">

**Comment by Lee-Jun-Young** [comment]
내가 올린 피알에서 validate 관련해서 수정한 부분이 있는데 아마 이것도 같이 수정이 될 것으로 예상은 가는데 저거 피알 받고 다시 한번 확인해줄 수 있을까????? 피알 합치고 해결되면 close 해주라~

**Comment by Lee-Jun-Young** [comment]
이거 혹시 지금도 재현되는지 확인해줄 수 있어???

**Comment by Ddudduu** [comment]
수정된 것 같아! 이슈 닫아놓을게!
