### ISSUE TITLE
여행 상세 -> 위시리스트,일정 생성시 태그에서 기타 제거

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#86]
기타 선택해서 위시리스트, 일정 추가하면

`{"category":["\"other\"이 유효하지 않은 선택(choice)입니다."]}`

응답이 옴!

**Comment by Lee-Jun-Young** [comment]
생성에서는 기타가 없구나~ 제거할게!

**Comment by Ddudduu** [comment]
지금 내가 바로 해도돼!

**Comment by Lee-Jun-Young** [comment]
오 그럼 부탁할게!!
