### ISSUE TITLE
여행 상세 -> 가계부 같은 날짜끼리 안묶이는 문제

### ISSUE THREAD

**Issue by Ddudduu** [prography-8th-6team/android#94]
- 같은 날짜에 생성된 비용은 한번에 묶여서 표시돼야 할 것 같아!
![detail](https://github.com/prography-8th-6team/android/assets/50603005/d8428baf-7e60-477b-a4e5-760142017073)

**Comment by Lee-Jun-Young** [comment]
이거 93번 이슈랑 같은 이슈라서 닫기 처리할게!!
